
import java.awt.Color;
import static java.awt.SystemColor.text;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.text.Highlighter.HighlightPainter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marcn
 */
public class Admin_Main extends javax.swing.JFrame {
    int sortchecker;
    FileReader records1;
    char[] record = new char[99999];
    
    // This variable "sortchecker" is used to store an integer value.
    // The "records1" variable is used to reference a FileReader object.
    // The "record" array is used to store a large number of characters.


    /**
     * Creates new form Admin_Main
     */
    public Admin_Main() {
        initComponents();
        
        Return.setBackground(new Color(0, 0, 0, 0));
        
        // This sets the background color of the "Return" object to a transparent color.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Return = new javax.swing.JButton();
        bimport = new javax.swing.JButton();
        bexport = new javax.swing.JButton();
        bprint2 = new javax.swing.JButton();
        bclear3 = new javax.swing.JButton();
        bsearch = new javax.swing.JButton();
        bclear2 = new javax.swing.JButton();
        recordsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Records = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        jPanel1.add(Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, 80));

        bimport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bimport.setText("IMPORT");
        bimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimportActionPerformed(evt);
            }
        });
        jPanel1.add(bimport, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 110, 40));

        bexport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bexport.setText("EXPORT");
        bexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexportActionPerformed(evt);
            }
        });
        jPanel1.add(bexport, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 120, 40));

        bprint2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bprint2.setText("PRINT TABLE");
        bprint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprint2ActionPerformed(evt);
            }
        });
        jPanel1.add(bprint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, 120, 40));

        bclear3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bclear3.setText("CLEAR TABLE");
        bclear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclear3ActionPerformed(evt);
            }
        });
        jPanel1.add(bclear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 590, 120, 40));

        bsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bsearch.setText("SEARCH");
        bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearchActionPerformed(evt);
            }
        });
        jPanel1.add(bsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, 110, 30));

        bclear2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bclear2.setText("CLEAR");
        bclear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclear2ActionPerformed(evt);
            }
        });
        jPanel1.add(bclear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 100, 30));

        recordsearch.setText("Date: ");
        recordsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                recordsearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                recordsearchFocusLost(evt);
            }
        });
        recordsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordsearchActionPerformed(evt);
            }
        });
        recordsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                recordsearchKeyPressed(evt);
            }
        });
        jPanel1.add(recordsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 450, 30));

        Records.setColumns(20);
        Records.setRows(5);
        Records.setEnabled(false);
        jScrollPane1.setViewportView(Records);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 910, 450));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("SEARCH RECORDS:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\marcn\\OneDrive\\Documents\\NetBeansProjects\\Techpoint\\src\\main\\java\\Images\\left part.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 780));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       
    }//GEN-LAST:event_jPanel1MouseDragged

    private void bimportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimportActionPerformed
        
        try {
            records1 = new FileReader("PatientRecords.txt");
            
            records1.read(record);
           
        
        } catch (IOException ex) {
            Logger.getLogger(Admin_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Records.append(String.valueOf(record));
        
        
        try {
            records1.close();
      
        } catch (IOException ex) {
            Logger.getLogger(Admin_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Records.setEnabled(true);
        
        
    }//GEN-LAST:event_bimportActionPerformed

    private void bexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexportActionPerformed
        
        
          try(PrintWriter output = new PrintWriter("OldRecords.txt")){

             output.println(Records.getText());
             
             
         } catch (FileNotFoundException ex) {
            Logger.getLogger(Admin_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
             
          
    }//GEN-LAST:event_bexportActionPerformed

    private void bprint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprint2ActionPerformed
        try{
            Records.print();
            
            // This code is attempting to print the contents of the "Records" object using the "print" method.
        }
        catch(java.awt.print.PrinterException e ){
            System.err.format("No printer found", e.getMessage());
        }

    }//GEN-LAST:event_bprint2ActionPerformed

    private void bclear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclear3ActionPerformed

        Records.setText("");
    }//GEN-LAST:event_bclear3ActionPerformed

    private void bsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearchActionPerformed
        String searchQuery = recordsearch.getText();
        
        Highlighter highlighter = Records.getHighlighter();
        HighlightPainter painter = new DefaultHighlighter.DefaultHighlightPainter(Color.yellow);
        
        int startIndex = Records.getText().indexOf(searchQuery);
        int endIndex = startIndex + searchQuery.length();

        
        try {
            highlighter.addHighlight(startIndex, endIndex, painter);
            
        } catch (BadLocationException ex) {
        }
        
    }//GEN-LAST:event_bsearchActionPerformed

    private void bclear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclear2ActionPerformed
        recordsearch.setText("");
        //This code sets the "recordsearch" object which is a textfield to an empty string removing all the text in it.
    }//GEN-LAST:event_bclear2ActionPerformed

    private void recordsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordsearchActionPerformed

    }//GEN-LAST:event_recordsearchActionPerformed

    private void recordsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recordsearchKeyPressed
       
    }//GEN-LAST:event_recordsearchKeyPressed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed

        Login_Page log = new Login_Page();

        log.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ReturnActionPerformed

    private void recordsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_recordsearchFocusGained

        recordsearch.setText("");
        
    }//GEN-LAST:event_recordsearchFocusGained

    private void recordsearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_recordsearchFocusLost

    }//GEN-LAST:event_recordsearchFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea Records;
    private javax.swing.JButton Return;
    private javax.swing.JButton bclear2;
    private javax.swing.JButton bclear3;
    private javax.swing.JButton bexport;
    private javax.swing.JButton bimport;
    private javax.swing.JButton bprint2;
    private javax.swing.JButton bsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField recordsearch;
    // End of variables declaration//GEN-END:variables
}
