
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class AppointmentUI extends javax.swing.JFrame{
    
    String age;
    String checkerA;
    String checkerB;
    String checkerC;
    String checkerD;
    
    int date;
    int cost;
    
    int cost1, cost2, cost3, cost4, cost5, cost6, cost7, cost8;
    String appointment = " ";
    
    
    AppointmentMethods AM = new AppointmentMethods();
    
    String DATE;
    
    
    public AppointmentUI() {
        initComponents();
        
        Return.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agegroup = new javax.swing.ButtonGroup();
        Therapy_App = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DateBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StatementArea = new javax.swing.JTextArea();
        childbutton = new javax.swing.JRadioButton();
        adultbutton = new javax.swing.JRadioButton();
        seniorbutton = new javax.swing.JRadioButton();
        SDT = new javax.swing.JRadioButton();
        AT = new javax.swing.JRadioButton();
        FT = new javax.swing.JRadioButton();
        DBT = new javax.swing.JRadioButton();
        RET = new javax.swing.JRadioButton();
        ET = new javax.swing.JRadioButton();
        PCT = new javax.swing.JRadioButton();
        GT = new javax.swing.JRadioButton();
        Return = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Patient Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 108, 390, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Patient Age:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Therapy Appointments:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 254, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Preferred Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 110, -1));

        DateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        DateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateBoxActionPerformed(evt);
            }
        });
        getContentPane().add(DateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 132, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Appointment Summary:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 303, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, 99, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 99, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 640, 93, 30));

        StatementArea.setColumns(20);
        StatementArea.setRows(5);
        jScrollPane1.setViewportView(StatementArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 540, 470));

        agegroup.add(childbutton);
        childbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        childbutton.setForeground(new java.awt.Color(0, 0, 0));
        childbutton.setText("Child");
        childbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(childbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, -1));

        agegroup.add(adultbutton);
        adultbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adultbutton.setForeground(new java.awt.Color(0, 0, 0));
        adultbutton.setText("Adult");
        adultbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(adultbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 60, -1));

        agegroup.add(seniorbutton);
        seniorbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seniorbutton.setForeground(new java.awt.Color(0, 0, 0));
        seniorbutton.setText("Senior");
        seniorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(seniorbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 70, -1));

        Therapy_App.add(SDT);
        SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SDT.setForeground(new java.awt.Color(0, 0, 0));
        SDT.setText("Systematic Desensitization Therapy");
        getContentPane().add(SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        Therapy_App.add(AT);
        AT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AT.setForeground(new java.awt.Color(0, 0, 0));
        AT.setText("Aversion Therapy");
        AT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATActionPerformed(evt);
            }
        });
        getContentPane().add(AT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        Therapy_App.add(FT);
        FT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FT.setForeground(new java.awt.Color(0, 0, 0));
        FT.setText("Flooding Therapy");
        getContentPane().add(FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        Therapy_App.add(DBT);
        DBT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DBT.setForeground(new java.awt.Color(0, 0, 0));
        DBT.setText("Dialectical Behavioral Therapy");
        getContentPane().add(DBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        Therapy_App.add(RET);
        RET.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RET.setForeground(new java.awt.Color(0, 0, 0));
        RET.setText("Rational Emotive Therapy");
        getContentPane().add(RET, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        Therapy_App.add(ET);
        ET.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ET.setForeground(new java.awt.Color(0, 0, 0));
        ET.setText("Existential Therapy");
        getContentPane().add(ET, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        Therapy_App.add(PCT);
        PCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PCT.setForeground(new java.awt.Color(0, 0, 0));
        PCT.setText("Person-Centered Therapy");
        getContentPane().add(PCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        Therapy_App.add(GT);
        GT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GT.setForeground(new java.awt.Color(0, 0, 0));
        GT.setText("Gestalt Therapy");
        getContentPane().add(GT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 100, 80));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Check");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 90, 30));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("-Combining relaxing exercises with gradual");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("exposure to fear.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 170, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("-Associates unwanted behaviour to");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 230, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("uncomfortable concepts to help stop it.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 220, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("-Treatment focused on facing the fear");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 230, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("head on.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 220, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("-Treatment that prioritizes acceptance");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 230, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("and emotional growth.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 220, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("-Learn how to challenge irrational beliefs");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 230, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("that contribute to emotional stress.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 220, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("-Philosophical approach; considering concepts");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 260, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("such as responsibility and freedom of choices.");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 250, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("-Focused on exercises to promote ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 230, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("self acceptance and growth.");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 220, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("-An approach that tackles unresolved issues");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 240, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("that might be affecting the well-being.");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\marcn\\OneDrive\\Documents\\NetBeansProjects\\Techpoint\\src\\main\\java\\Images\\right part.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateBoxActionPerformed
        // TODO add your handling code here:
        DATE = DateBox.getSelectedItem().toString();
        date = Integer.parseInt(DATE);
        
        /* This code is getting the currently selected item from the "DateBox" object, which is a dropdown menu.
         The selected item is then converted to a string and stored in the "DATE" variable.
         The string value of "DATE" is then parsed as an integer and stored in the "date" variable.
         This is useful since the selected item in the "DateBox" object represents a numerical value, 
         and it is the day of the month.*/
    }//GEN-LAST:event_DateBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        cost = 0;
        
        if (SDT.isSelected()){
            cost1 = 4000;
            appointment = "Systematic Desensitization Therapy ";
        }
        if (AT.isSelected()){
            cost2 = 4000;
            appointment = "Aversion Therapy ";
        }
        if (FT.isSelected()){
            cost3 = 4000;
            appointment = "Flooding Therapy ";
        }
        if (DBT.isSelected()){
            cost4 = 3000;
            appointment = "Dialectical Behavioral Therapy ";
        }
        if (RET.isSelected()){
            cost5 = 3000;
            appointment = "Rational Emotive Therapy ";
        }
        if (ET.isSelected()){
            cost6 = 1500;
            appointment = "Existential Therapy ";
        }
        if (PCT.isSelected()){
            cost7 = 1500;
            appointment = "Person-Centered Therapy ";
        }
        if (GT.isSelected()){
            cost8 = 1500;
            appointment = "Gestalt Therapy ";
        }
        cost = cost1 + cost2 + cost3 + cost4 + cost5 + cost6 + cost7 + cost8;
        String services = appointment;
        
        
        AM.makeAppointment(jTextField1.getText(), age , cost, date, services);
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cost = 0;
        jTextField1.setText("");
        StatementArea.setText("");
        SDT.setSelected(false);
        AT.setSelected(false);
        FT.setSelected(false);
        DBT.setSelected(false);
        RET.setSelected(false);
        ET.setSelected(false);
        PCT.setSelected(false);
        GT.setSelected(false);
        
        
        cost1 = 0;
        cost2 = 0;
        cost3 = 0;
        cost4 = 0;
        cost5 = 0;
        cost6 = 0;
        cost7 = 0;
        cost8 = 0;
        
        appointment = "";
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void adultbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultbuttonActionPerformed
        // TODO add your handling code here:
        age = "Adult";
        
        // This code is assigning the string value "Adult" to the "age" variable.
    }//GEN-LAST:event_adultbuttonActionPerformed

    private void seniorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorbuttonActionPerformed
        // TODO add your handling code here:
        age = "Senior";
        
        // This code is assigning the string value "Senior" to the "age" variable.
    }//GEN-LAST:event_seniorbuttonActionPerformed

    private void childbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childbuttonActionPerformed
        // TODO add your handling code here:
        age = "Child";
        
        // This code is assigning the string value "Child" to the "age" variable.
    }//GEN-LAST:event_childbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
        //AppointmentMethods AM = new AppointmentMethods();
        
        AM.Print();
        
        /* This code is calling the "Print" method of the "AM" objects which prints
        the data into a txt file to create a temporary database.*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
        
        Login_Page log = new Login_Page();
        
        log.setVisible(true);
        dispose();
        
        // This code is creating a new object of the "Login_Page" class and making it visible to the user.
        // This will return the user back to the login page. 
        /* The "dispose" method is then called on the current object, which closes it 
        and releases any system resources associated with it.*/
    }//GEN-LAST:event_ReturnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cost = 0;
        
        if (SDT.isSelected()){
            cost1 = 4000;
            appointment = "Systematic Desensitization Therapy ";
        }
        if (AT.isSelected()){
            cost2 = 4000;
            appointment = "Aversion Therapy ";
        }
        if (FT.isSelected()){
            cost3 = 4000;
            appointment = "Flooding Therapy ";
        }
        if (DBT.isSelected()){
            cost4 = 3000;
            appointment = "Dialectical Behavioral Therapy ";
        }
        if (RET.isSelected()){
            cost5 = 3000;
            appointment = "Rational Emotive Therapy ";
        }
        if (ET.isSelected()){
            cost6 = 1500;
            appointment = "Existential Therapy ";
        }
        if (PCT.isSelected()){
            cost7 = 1500;
            appointment = "Person-Centered Therapy ";
        }
        if (GT.isSelected()){
            cost8 = 1500;
            appointment = "Gestalt Therapy ";
        }
        cost = cost1 + cost2 + cost3 + cost4 + cost5 + cost6 + cost7 + cost8;
        String services = appointment;
        
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Name is missing.");
        }
        if (childbutton.isSelected()||adultbutton.isSelected()||seniorbutton.isSelected()){
            checkerA = age;
        }else{JOptionPane.showMessageDialog(this, "Age is missing.");}
        if(SDT.isSelected() || 
                AT.isSelected() || 
                FT.isSelected() || 
                DBT.isSelected() || 
                RET.isSelected() || 
                ET.isSelected() || 
                PCT.isSelected() || 
                GT.isSelected()){
            checkerB = appointment;
        }else{JOptionPane.showMessageDialog(this, "Therapy session is missing.");}
        if(date != 0){
            checkerC = Integer.toString(date);
        }else{JOptionPane.showMessageDialog(this, "Date is missing.");}
        
        
        
        StatementArea.setText(
                "Patient Name: " + jTextField1.getText() +
                "\nPatient Age: " + age +
                "\nAppointment Cost: " + cost +
                "\nAppointment Date: " + date +
                "\nServices: " + services + "\n"
        );
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        AM.removeItem();
        AM.Print();
        
    // This code is calling the "removeItem" method of the "AM" object and then calling the "Print" method of the same object.
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ATActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentUI().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AT;
    private javax.swing.JRadioButton DBT;
    private javax.swing.JComboBox<String> DateBox;
    private javax.swing.JRadioButton ET;
    private javax.swing.JRadioButton FT;
    private javax.swing.JRadioButton GT;
    private javax.swing.JRadioButton PCT;
    private javax.swing.JRadioButton RET;
    private javax.swing.JButton Return;
    private javax.swing.JRadioButton SDT;
    public javax.swing.JTextArea StatementArea;
    private javax.swing.ButtonGroup Therapy_App;
    private javax.swing.JRadioButton adultbutton;
    private javax.swing.ButtonGroup agegroup;
    private javax.swing.JRadioButton childbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton seniorbutton;
    // End of variables declaration//GEN-END:variables
}
